services:
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./opt-esus:/opt/e-SUS
      - ./backups:/backups
    build:
      context: .
      dockerfile: Dockerfile.external-db
      args:
        - TZ=${TZ}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - HTTPS_DOMAIN=${HTTPS_DOMAIN}
      tags:
        - ${VERSION:-latest}
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"